server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/person?serverTimezone=Asia/Shanghai
    password: '0002'
    username: root
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml

